In [2]:
print("Kernel Works")

Kernel Works

## Import

In [3]:
import pandas as pd 
import numpy as np

## Load in NFL Data

In [4]:
url = "https://raw.githubusercontent.com/nflverse/nfldata/master/data/games.csv"
games = pd.read_csv(url)

In [5]:
games.head()

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,...,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
0,1999_01_MIN_ATL,1999,REG,1,1999-09-12,Sunday,NaN,MIN,17.0,ATL,...,NaN,00-0003761,00-0002876,Randall Cunningham,Chris Chandler,Dennis Green,Dan Reeves,Gerry Austin,ATL00,Georgia Dome
1,1999_01_KC_CHI,1999,REG,1,1999-09-12,Sunday,NaN,KC,17.0,CHI,...,12.0,00-0006300,00-0010560,Elvis Grbac,Shane Matthews,Gunther Cunningham,Dick Jauron,Phil Luckett,CHI98,Soldier Field
2,1999_01_PIT_CLE,1999,REG,1,1999-09-12,Sunday,NaN,PIT,43.0,CLE,...,12.0,00-0015700,00-0004230,Kordell Stewart,Ty Detmer,Bill Cowher,Chris Palmer,Bob McElwee,CLE00,Cleveland Browns Stadium
3,1999_01_OAK_GB,1999,REG,1,1999-09-12,Sunday,NaN,OAK,24.0,GB,...,10.0,00-0005741,00-0005106,Rich Gannon,Brett Favre,Jon Gruden,Ray Rhodes,Tony Corrente,GNB00,Lambeau Field
4,1999_01_BUF_IND,1999,REG,1,1999-09-12,Sunday,NaN,BUF,14.0,IND,...,NaN,00-0005363,00-0010346,Doug Flutie,Peyton Manning,Wade Phillips,Jim Mora,Ron Blum,IND99,RCA Dome

In [6]:
games.shape

(7548, 46)

In [7]:
games.columns.tolist()

['game_id',
 'season',
 'game_type',
 'week',
 'gameday',
 'weekday',
 'gametime',
 'away_team',
 'away_score',
 'home_team',
 'home_score',
 'location',
 'result',
 'total',
 'overtime',
 'old_game_id',
 'gsis',
 'nfl_detail_id',
 'pfr',
 'pff',
 'espn',
 'ftn',
 'away_rest',
 'home_rest',
 'away_moneyline',
 'home_moneyline',
 'spread_line',
 'away_spread_odds',
 'home_spread_odds',
 'total_line',
 'under_odds',
 'over_odds',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'away_qb_id',
 'home_qb_id',
 'away_qb_name',
 'home_qb_name',
 'away_coach',
 'home_coach',
 'referee',
 'stadium_id',
 'stadium']

## Set to the important columns

In [8]:
games [[
    "season", 
    "week", 
    "gameday",
    "away_team",
    "away_score",
    "home_team",
    "home_score",
    "spread_line",
    "total_line"
]].head(10)

,season,week,gameday,away_team,away_score,home_team,home_score,spread_line,total_line
0,1999,1,1999-09-12,MIN,17.0,ATL,14.0,-4.0,49.0
1,1999,1,1999-09-12,KC,17.0,CHI,20.0,-3.0,38.0
2,1999,1,1999-09-12,PIT,43.0,CLE,0.0,-6.0,37.0
3,1999,1,1999-09-12,OAK,24.0,GB,28.0,9.0,43.0
4,1999,1,1999-09-12,BUF,14.0,IND,31.0,-3.0,45.5
5,1999,1,1999-09-12,SF,3.0,JAX,41.0,5.5,49.0
6,1999,1,1999-09-12,CAR,10.0,NO,19.0,3.5,38.0
7,1999,1,1999-09-12,NE,30.0,NYJ,28.0,7.0,44.5
8,1999,1,1999-09-12,ARI,25.0,PHI,24.0,-3.0,37.0
9,1999,1,1999-09-12,DET,28.0,SEA,20.0,9.5,42.0

In [10]:
## Filter to 2018 - 2026
nfl = games[
    (games["season"] >= 2015) & 
    (games["season"] <= 2025)
].copy()

In [11]:
nfl.shape

(3028, 46)

In [12]:
nfl["margin"] = nfl["home_score"] - nfl["away_score"]

In [13]:
nfl[[
    "season",
    "week",
    "away_team",
    "away_score",
    "home_team",
    "home_score",
    "margin",
    "spread_line"
]].head(10)

,season,week,away_team,away_score,home_team,home_score,margin,spread_line
4248,2015,1,PIT,21.0,NE,28.0,7.0,7.5
4249,2015,1,IND,14.0,BUF,27.0,13.0,-1.0
4250,2015,1,GB,31.0,CHI,23.0,-8.0,-5.5
4251,2015,1,KC,27.0,HOU,20.0,-7.0,-1.0
4252,2015,1,CAR,20.0,JAX,9.0,-11.0,-3.0
4253,2015,1,CLE,10.0,NYJ,31.0,21.0,3.5
4254,2015,1,SEA,31.0,STL,34.0,3.0,-3.5
4255,2015,1,MIA,17.0,WAS,10.0,-7.0,-4.0
4256,2015,1,NO,19.0,ARI,31.0,12.0,2.0
4257,2015,1,DET,28.0,SD,33.0,5.0,3.5

## Check data quality

In [14]:
nfl[["home_score", "away_score", "spread_line", "margin"]].isnull().sum()

home_score     0
away_score     0
spread_line    0
margin         0
dtype: int64

In [15]:
nfl["season"].value_counts().sort_index()

season
2015    267
2016    267
2017    267
2018    267
2019    267
2020    269
2021    285
2022    284
2023    285
2024    285
2025    285
Name: count, dtype: int64

In [17]:
nfl["margin"].describe()

count    3028.000000
mean        1.897952
std        14.162531
min       -49.000000
25%        -7.000000
50%         3.000000
75%        10.000000
max        50.000000
Name: margin, dtype: float64